version: '3.8'

services:

  traefik:
    image: traefik
    container_name: proxy01
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8081"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tonemail@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./Traefik/letsencrypt:/letsencrypt
    networks:
      - front


  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: web01
    restart: always
    volumes:
      - ./PHP:/var/www/html
      - ./Apache/static:/var/www/html/static
    networks:
      - front
      - back
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`tondomaine.com`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=myresolver"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: web02
    restart: always
    volumes:
      - ./PHP:/var/www/html/php
      - ./Nginx/static:/var/www/html/static
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - front
      - back
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`tondomaine.com`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=myresolver"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

  php-fpm:
    build: ./PHP
    container_name: php-fpm
    restart: always
    volumes:
      - ./PHP:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - front
      - back

  postgres:
    image: postgres
    container_name: db01
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
