version: "3.8"

services:

  traefik:
    image: traefik
    container_name: proxy01
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./Traefik/certs:/certs
    networks:
      - front
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.28.0.10:514"

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: web01
    volumes:
      - ./PHP:/var/www/html
    networks:
      - front
      - back
    expose:
      - "80"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.28.0.10:514"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: web02
    depends_on:
      - php-fpm
    volumes:
      - ./PHP:/var/www/html/php
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front
      - back
    expose:
      - "80"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.28.0.10:514"

  php-fpm:
    build: ./PHP
    container_name: php-fpm
    volumes:
      - ./PHP:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - front
      - back
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.28.0.10:514"

  db01:
    image: postgres
    container_name: db01
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back
      - front
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.28.0.10:514"

  rsyslog:
    build:
      context: ./rsyslog
      dockerfile: Dockerfile
    container_name: rsyslog
    ports:
      - "514:514/udp"
    volumes:
      - ./rsyslog/config:/etc/rsyslog.d
      - ./rsyslog/log:/var/log
    networks:
      front:
        ipv4_address: 172.28.0.10
      back:
        ipv4_address: 172.29.0.10
    restart: always

networks:
  front:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
