tls:
  certificates:
    - certFile: "/certs/selfsigned.crt"
      keyFile: "/certs/selfsigned.key"

http:
  routers:
    web:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: web
    websecure:
      rule: "Host(`reseau.localhost`)"
      entryPoints:
        - websecure
      service: web
      tls: true
    traefik-dashboard:
      rule: "Host(`traefik.localhost`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: true

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    web:
      loadBalancer:
        sticky:
          cookie:
            name: "MYSESSION"
            httpOnly: true
            secure: true
        servers:
          - url: "http://web01:80"
          - url: "http://web02:80"
