http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  routers:
    web:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: web

  services:
    web:
      loadBalancer:
        servers:
          - url: "http://web01:80"
          - url: "http://web02:80"
